drop DATABASE mokdb;

CREATE DATABASE mokdb;
use mokdb;
CREATE TABLE TB_USUARIO (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NM_USUARIO VARCHAR(200),
    DS_EMAIL VARCHAR(200),
    DS_SENHA VARCHAR(20),
    DT_CRIACAO DATETIME
);

CREATE TABLE TB_MENSAGEM (
    ID_MENSAGEM INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO_ENVIO INT,
    ID_USUARIO_PARA INT,
    ID_SALA INT,
    DS_MENSAGEM VARCHAR(200),
    DT_MENSAGEM DATETIME,
    FOREIGN KEY (ID_USUARIO_ENVIO) REFERENCES TB_USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_USUARIO_PARA) REFERENCES TB_USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_SALA) REFERENCES TB_SALA(ID_SALA)
);

CREATE TABLE TB_SALA (
    ID_SALA INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    NM_SALA VARCHAR(200),
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO)
);

CREATE TABLE TB_PARTICIPANTE (
    ID_PARTICIPANTE INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    ID_SALA INT,
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_SALA) REFERENCES TB_SALA(ID_SALA)
);

select * from tb_usuario;